<br></br>
<h2>How to Use Planworld</h2>

<p>Welcome to Planworld! If you're new to our little community, Planworld is basically a social network from a time before MySpace and Facebook, built by and for the Amherst community. You can read about the history and driving philosophy behind Planworld <a href="index.php?id=about">here</a>.</p>
<br></br>

<h3>Getting Started</h3>
<p>To get the most out of planworld, just start <a href="index.php?id=edit_plan">updating your plan</a>. It doesn't have to be anything fancy, what's most important is getting the words out.</p>

<p>Subscribe to other people you know who may be on planworld by "fingering" their username using the search box at the top-right of the page. If you find someone you'd like to follow, click "Add to my planwatch" above their username in their plan body. Once followed, they will be added to your the list of plans on the left side of your screen--your Planwatch.</p>

<p>Planworld strives to be an open and inclusive community, so feel free to follow people you don't know as well! Some planworld notables include <a href="?id=rbilton10">rbilton10</a>, <a href="?id=dahardawar">dahardawar</a>, <a href="?id=cfvandijk03">cfvandijk03</a>, and <a href="?id=mppai99">mppai99</a>.</p>

<p>You can also organize your planwatch by clicking "Edit" to the right of the top of planwatch. Here you can add other users to your planwatch manually, and in batch groups. You can also organize your planwatch into "groups" to better organize who you're following.</p>
<br></br>

<h3>The Top Menu</h3>

<p><strong>Look:</strong> Shows you all of your currently unread plans on a single page. This is an older feature that was recently revived. Take note that it clears your entire planwatch as read.</p>

<p><strong>Stats:</strong> Gives some quick statistics on your plan and all of Planworld.</p>

<p><strong>Snitch:</strong> Allows you to see who recently read your plan. Take note that you also show up on someones snitch list when you read their plan. If you want to browse plans anonymously, you can turn it off by disabling the Snitch Tracker in preferences. When you do this, you will <strong>not</strong> be able to see who reads your plan. Basically, we advise you not to turn off snitch.</p>

<p><strong>Snoop:</strong> Tracks who has referenced your plan on Planworld. You can snoop anyone in your plan by referencing their plan as <strong>!username!</strong> . You can also reference them with text by using <strong>!username:Text description here!</strong> . Snoops also appear on the left menu below your Planwatch.</p>

<p><strong>Preferences:</strong> Offers several other ways to customize your plan. You can change the type of plan, your theme, and also the way you view your planwatch, among other options.</p>

<p><strong>FAQ:</strong> Offers some general Planworld advice not covered by this document.</p>

<p><strong>About:</strong> A wonderful retelling of the history of planworld, along with our community philosophy, by Planworld rock star <a href="?id=jlodom00">jlodom00</a>. If you fall in love with planworld like many before you, be sure to read this to know why Planworld is such an integral part of Amherst.</p>
<br></br>

<h3>Archives</h3>
<p>Your Planworld archives are public by default, but you have the ability to make them all private in your preferences. Otherwise, you can make individual posts private by clicking the Archives button on the top-right section of your screen.</p>